version: "3.2"
services:
  terraform:
    build:
      dockerfile: Dockerfile
    volumes:
      - $PWD/terraform:/app
      - $PWD/kubeconf:/kubeconf
    working_dir: /app
    network_mode: host
    entrypoint: /bin/sh
    tty: true
    restart: no