apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations: {}
  name: acme-issuer
  namespace: cert-manager
spec:
  acme:
    privateKeySecretRef:
      name: acme-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            ingressClassName: haproxy
