{{- if empty .Values.mysql.config.rootPassword.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.mysql.rootPasswordSecret" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "wordpress.mysql.rootPasswordSecret" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secret := (get $secretData (include "wordpress.mysql.rootPasswordSecretKey" .)) | default (include "wordpress.mysql.rootPassword" .) }}
  {{ include "wordpress.mysql.rootPasswordSecretKey" . }}: {{ $secret | quote }}
{{- end }}
---
{{- if empty .Values.mysql.config.dbAuth.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.mysql.authSecret" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "wordpress.mysql.authSecret" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretUser := (get $secretData (include "wordpress.mysql.authUserSecretKey" .)) | default (include "wordpress.mysql.authUsername" .) }}
  {{ include "wordpress.mysql.authUserSecretKey" . }}: {{ $secretUser | quote }}
  {{- $secretPass := (get $secretData (include "wordpress.mysql.authPassSecretKey" .)) | default (include "wordpress.mysql.authPassword" .) }}
  {{ include "wordpress.mysql.authPassSecretKey" . }}: {{ $secretPass | quote }}
{{- end }}
---
{{- if or (empty .Values.wordpress.config.wordpressUsername.secretRef) (empty .Values.wordpress.config.wordpressPassword.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.wp.authSecret" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "wordpress.wp.authSecret" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if empty .Values.wordpress.config.wordpressUsername.secretRef }}
  {{- $data := (get $secretData (include "wordpress.wp.authUserSecretKey" .)) | default (include "wordpress.wp.authUsername" .) }}
  {{ include "wordpress.wp.authUserSecretKey" . }}: {{ $data | quote }}
  {{- end }}
  {{- if empty .Values.wordpress.config.wordpressPassword.secretRef }}
  {{- $data := (get $secretData (include "wordpress.wp.authPassSecretKey" .)) | default (include "wordpress.wp.authPassword" .) }}
  {{ include "wordpress.wp.authPassSecretKey" . }}: {{ $data | quote }}
  {{- end }}
{{- end }}