apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.mysql.type }}
  selector:
    app: mysql
  ports:
    - port: {{ .Values.service.mysql.port }}
      protocol: TCP
      name: mysql
  clusterIP: "None"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.phpmyadmin.type }}
  selector:
    app: phpmyadmin
  ports:
    - port: {{ .Values.service.phpmyadmin.port }}
      protocol: TCP
      name: web
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.wordpress.type }}
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.service.wordpress.port }}
      protocol: TCP
      name: wordpress