apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations.mysql }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: mysql
        {{- with .Values.podLabels.mysql }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.mysql.rootPasswordSecret" . }}
                  key: {{ include "wordpress.mysql.rootPasswordSecretKey" . }}
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wordpress.mysql.dbConfigmap" . }}
                  key: {{ include "wordpress.mysql.dbConfigmapKey" . }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.mysql.authSecret" . }}
                  key: {{ include "wordpress.mysql.authUserSecretKey" . }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.mysql.authSecret" . }}
                  key: {{ include "wordpress.mysql.authPassSecretKey" . }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
            {{- with .Values.volumeMounts.mysql }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources.mysql | nindent 12 }}
      {{- with .Values.volumes.mysql }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi